config {
  type: "table",
  schema: "raw_vault",
  tags: ["hub"]
}

SELECT
  MD5(PassengerID) AS HK_PassengerID,
  PassengerID,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'undefined' AS REC_SRC
FROM ${ref("undefined")}
WHERE PassengerID IS NOT NULL
GROUP BY PassengerID
UNION ALL
SELECT
  MD5(PassengerID) AS HK_PassengerID,
  PassengerID,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'undefined' AS REC_SRC
FROM ${ref("undefined")}
WHERE PassengerID IS NOT NULL
GROUP BY PassengerID