config {
  type: "table",
  schema: "raw_vault",
  tags: ["satellite"]
}

SELECT
  MD5(PassengerID) AS HK_PassengerID,
  MD5(CONCAT(COALESCE(column1, ''), '|', COALESCE(column2, ''), '|', ...)) AS HASHDIFF,
  FirstName,
  LastName,
  DOB,
  Email,
  CreatedDateTime,
  LastupdateDateTime,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_PASSENGER_DETAILS' AS REC_SRC
FROM ${ref("AI_PASSENGER_DETAILS")}
WHERE PassengerID IS NOT NULL