config {
  type: "table",
  schema: "raw_vault",
  tags: ["satellite"]
}

SELECT
  MD5(BookingID) AS HK_BookingID,
  Status,
  BookingDate,
  SeatNumber,
  SeatClass,
  CreatedDateTime,
  LastupdateDateTime,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  '' AS REC_SRC
FROM ${ref("")}
WHERE BookingID IS NOT NULL
GROUP BY BookingID, Status, BookingDate, SeatNumber, SeatClass, CreatedDateTime, LastupdateDateTime