config {
  type: "table",
  schema: "raw_vault",
  tags: ["satellite"]
}

SELECT
  MD5(FlightID) AS HK_FlightID,
  MD5(CONCAT(COALESCE(CAST(FlightNumber AS STRING), ''), '|', COALESCE(CAST(ArrivalDateTime AS STRING), ''), '|', COALESCE(CAST(ScheduledDepartureDateTime AS STRING), ''), '|', COALESCE(CAST(ActualDepartureDateTime AS STRING), ''), '|', COALESCE(CAST(OriginAirportCode AS STRING), ''), '|', COALESCE(CAST(DestinationAirportCode AS STRING), ''), '|', COALESCE(CAST(SeatCapacity AS STRING), ''), '|', COALESCE(CAST(AvailableSeats AS STRING), ''))) AS HASHDIFF,
  FlightNumber,
  ArrivalDateTime,
  ScheduledDepartureDateTime,
  ActualDepartureDateTime,
  OriginAirportCode,
  DestinationAirportCode,
  SeatCapacity,
  AvailableSeats,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_FLIGHT_DETAILS' AS REC_SRC
FROM ${ref("AI_FLIGHT_DETAILS")}
WHERE FlightID IS NOT NULL