config {
  type: "table",
  bigquery: { partitionBy: "DATE(LOAD_DTS)", clusterBy: ["HK_AirportCode"] },
  schema: "raw_vault",
  tags: ["satellite"]
}

SELECT
  MD5(PaymentID) AS HK_PaymentID,
  PaymentMethod,
  Amount,
  TransactionDate,
  Status,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_PAYMENT' AS REC_SRC
FROM ${ref("AI_PAYMENT")}
WHERE PaymentID IS NOT NULL
GROUP BY PaymentID, PaymentMethod, Amount, TransactionDate, Status