config {
  type: "table",
  schema: "raw_vault",
  tags: ["satellite"]
}

SELECT
  MD5(PassengerID) AS HK_PassengerID,
  MD5(CONCAT(COALESCE(CAST(FirstName AS STRING), ''), '|', COALESCE(CAST(LastName AS STRING), ''), '|', COALESCE(CAST(DOB AS STRING), ''), '|', COALESCE(CAST(Email AS STRING), ''), '|', COALESCE(CAST(CreatedDateTime AS STRING), ''), '|', COALESCE(CAST(LastupdateDateTime AS STRING), ''))) AS HASHDIFF,
  FirstName,
  LastName,
  DOB,
  Email,
  CreatedDateTime,
  LastupdateDateTime,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'Passenger_Details_Test' AS REC_SRC
FROM ${ref("Passenger_Details_Test")}
WHERE PassengerID IS NOT NULL