config {
  type: "table",
  schema: "raw_vault",
  tags: ["satellite"]
}

SELECT
  MD5(BookingID) AS HK_BookingID,
  MD5(CONCAT(COALESCE(CAST(FlightID AS STRING), ''), '|', COALESCE(CAST(PassengerID AS STRING), ''), '|', COALESCE(CAST(Status AS STRING), ''), '|', COALESCE(CAST(BookingDate AS STRING), ''), '|', COALESCE(CAST(SeatNumber AS STRING), ''), '|', COALESCE(CAST(SeatClass AS STRING), ''), '|', COALESCE(CAST(PaymentID AS STRING), ''), '|', COALESCE(CAST(CreatedDateTime AS STRING), ''), '|', COALESCE(CAST(LastupdateDateTime AS STRING), ''))) AS HASHDIFF,
  FlightID,
  PassengerID,
  Status,
  BookingDate,
  SeatNumber,
  SeatClass,
  PaymentID,
  CreatedDateTime,
  LastupdateDateTime,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_BOOKING_DETAILS' AS REC_SRC
FROM ${ref("AI_BOOKING_DETAILS")}
WHERE BookingID IS NOT NULL