config {
  type: "table",
  schema: "raw_vault",
  tags: ["hub"]
}

SELECT MD5(AirportCode) AS HK_AirportCode,
  AirportCode,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_AIRPORT' AS REC_SRC
FROM ${ref("AI_AIRPORT_DETAILS")}
WHERE AirportCode IS NOT NULL
GROUP BY AirportCode

UNION ALL

SELECT MD5(AirportCode) AS HK_AirportCode,
  AirportCode,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'SJ_AIRPORT' AS REC_SRC
FROM ${ref("SJ_AIRPORT_DETAILS")}
WHERE AirportCode IS NOT NULL
GROUP BY AirportCode