config {
  type: "table",
  schema: "raw_vault",
  tags: ["hub"]
}

SELECT MD5(FlightID) AS HK_FlightID,
  FlightID,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_PASSENGER' AS REC_SRC
FROM sky-vault-473510.staging.AI_FLIGHT_DETAILS
WHERE FlightID IS NOT NULL
GROUP BY FlightID

UNION ALL

SELECT MD5(FlightID) AS HK_FlightID,
  FlightID,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'SJ_PASSENGER' AS REC_SRC
FROM sky-vault-473510.staging.SJ_FLIGHT_DETAILS
WHERE FlightID IS NOT NULL
GROUP BY FlightID