
config {
  type: "table",
  schema: "raw_vault",
  tags: ["hub"]
}

SELECT
  MD5(FlightID) AS HK_FlightID,
  FlightID,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_FLIGHT_DETAILS' AS REC_SRC
FROM ${ref("AI_FLIGHT_DETAILS")}
WHERE FlightID IS NOT NULL
GROUP BY FlightID;



config {
  type: "table",
  schema: "raw_vault",
  tags: ["hub"]
}

SELECT
  MD5(AirportCode) AS HK_AirportCode,
  AirportCode,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_AIRPORT_DETAILS' AS REC_SRC
FROM ${ref("AI_AIRPORT_DETAILS")}
WHERE AirportCode IS NOT NULL
GROUP BY AirportCode;
