config {
  type: "table",
  schema: "raw_vault",
  tags: ["sat"]
}

SELECT MD5(FlightID) AS HK_FlightID,
  FlightNumber,
  ArrivalDateTime,
  ScheduledDepartureDateTime,
  ActualDepartureDateTime,
  SeatCapacity,
  AvailableSeats,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_FLIGHT' AS REC_SRC
FROM sky-vault-473510.staging.AI_FLIGHT_DETAILS
WHERE FlightID IS NOT NULL

UNION ALL

SELECT MD5(FlightID) AS HK_FlightID,
    FlightNumber,
  ArrivalDateTime,
  ScheduledDepartureDateTime,
  ActualDepartureDateTime,
  SeatCapacity,
  AvailableSeats,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'SJ_FLIGHT' AS REC_SRC
FROM sky-vault-473510.staging.SJ_FLIGHT_DETAILS
WHERE FlightID IS NOT NULL