config {
  type: "table",
  schema: "raw_vault",
  tags: ["hub"]
}

SELECT MD5(PassengerID) AS HK_PassengerID,
  FirstName,
  LastName,
  DOB,
  Email,
  MobileNumber,
  CreatedDateTime,
  LastupdateDateTime,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_PASSENGER' AS REC_SRC
FROM sky-vault-473510.staging.AI_PASSENGER_DETAILS
WHERE PassengerID IS NOT NULL

UNION ALL

SELECT MD5(PassengerID) AS HK_PassengerID,
  FirstName,
  LastName,
  DOB,
  Email,
  MobileNumber,
  CreatedDateTime,
  LastupdateDateTime,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'SJ_PASSENGER' AS REC_SRC
FROM sky-vault-473510.staging.SJ_PASSENGER_DETAILS
WHERE PassengerID IS NOT NULL