config {
  type: "table",
  schema: "raw_vault",
  tags: ["sat"]
}

SELECT MD5(AirportCode) AS HK_AirportCode,
  AirportCode,
  AirportName,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'AI_AIRPORT' AS REC_SRC
FROM sky-vault-473510.staging.AI_AIRPORT_DETAILS
WHERE AirportCode IS NOT NULL

UNION ALL

SELECT MD5(AirportCode) AS HK_AirportCode,
  AirportCode,
  AirportName,
  CURRENT_TIMESTAMP() AS LOAD_DTS,
  'SJ_AIRPORT' AS REC_SRC
FROM sky-vault-473510.staging.SJ_AIRPORT_DETAILS
WHERE AirportCode IS NOT NULL